name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Sync files to EC2
        run: |
          rsync -avz --exclude '.git' --exclude 'node_modules' \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/skaya-frontend

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/skaya-frontend
            docker compose down
            docker compose up -d --build
            sudo systemctl restart nginx
          EOF
