name: Auto-Deploy Skaya Frontend

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 via Docker
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/skaya-frontend
            git pull origin main

            # Build Docker image
            docker build -t skaya-frontend .

            # Stop and remove old container if it exists
            docker rm -f skaya-frontend || true

            # Run new container
            docker run -d -p 80:80 --name skaya-frontend skaya-frontend
          EOF
