name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/skaya-frontend || mkdir ~/skaya-frontend && cd ~/skaya-frontend

            # Pull latest code
            git reset --hard
            git pull

            # Stop and remove old container if exists
            docker rm -f skaya-frontend || true

            # Remove old image
            docker rmi -f skaya-frontend || true

            # Build new Docker image
            docker build -t skaya-frontend .

            # Run new container
            docker run -d -p 8080:80 --name skaya-frontend skaya-frontend

            # Optional: clean up dangling images
            docker image prune -f
          EOF
